# permissions for end users to view processdumps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: processdump-viewer-role
rules:
- apiGroups:
  - diagnostics.office.com
  resources:
  - processdumps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - diagnostics.office.com
  resources:
  - processdumps/status
  verbs:
  - get
