# permissions for end users to edit processdumps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: processdump-editor-role
rules:
- apiGroups:
  - diagnostics.office.com
  resources:
  - processdumps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnostics.office.com
  resources:
  - processdumps/status
  verbs:
  - get
